### ISSUE TITLE
`gist` scope may be unnecessary

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/giscus#15]
I read this for the `(no scope)` section on scopes and originally added the `gist` scope because I thought this meant the `(no scope)` default didn't get access to secret gists. But now, I'm reading it, and I'm thinking it may be possible instead that you only need the `gist` scope if you need *write* access, which we clearly don't.

> Grants read-only access to public information (includes public user profile info, public repository info, and gists)

I think I may have misunderstood, and we may be able to get away without `gist` scope. Anyone know?

https://developer.github.com/v3/oauth/#scopes

**Comment by adamwathan** [comment]
Just tested, `no scope` only returns public gists.

FYI quickest way to test this stuff, go here: https://github.com/settings/tokens

You can quickly create tokens for yourself with whatever scopes you want and then just hit the GitHub API with Postman/Paw/whatevs :+1:

**Comment by mattstauffer** [comment]
Thanks Adam! I didn't know you could do that. Mission accomplished. :) now to get GitHub to update their docs. 

Sent from Outlook




On Fri, Sep 11, 2015 at 3:59 AM -0700, "Adam Wathan" <notifications@github.com> wrote:












Just tested, no scope only returns public gists.



FYI quickest way to test this stuff, go here: https://github.com/settings/tokens



You can quickly create tokens for yourself with whatever scopes you want and then just hit the GitHub API with Postman/Paw/whatevs

**Comment by dragon788** [comment]
Have you modified this so a user can request "no scope" and only have their public gists accessible?

**Comment by mattstauffer** [comment]
@dragon788 nope. But if that's something you're interested in, please feel free to open a new issue about it. Thanks!
