### ISSUE TITLE
If user credentials go bad, delete and notify the user

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/giscus#17]
We're getting errors in the logs like this:

```
[2016-01-21 04:02:59] production.INFO: Attempting to queue "get comments" for user 160 after GitHub exception. Delayed exceution for 60 minutes after (9) attempts. Message: [Bad credentials] Exception class: [Github\Exception\RuntimeException]
```

(also, note that typo in exceution)
First, let's see if we can get any information about why the credentials are being marked as bad. Second, if it just means something like "user rejected our token", then let's delete their account and send them an email notifying them of what's happened and providing instructions on how to reinstate their account if they'd like.

**Comment by DanielDarrenJones** [comment]
Having trouble getting the source to run locally, but If I had to hazard a guess this error would be caused when the user manually removes the application from their oAuth application on github without revoking via the Giscus site.

**Comment by JesusLeon** [comment]
Hi @mattstauffer, I've created the PR #22. Hopefully that it works for you.

**Comment by DanielDarrenJones** [comment]
@JesusLeon that looks really good.

Only small suggestion would possibly be queueing the email to be sent. But otherwise looks pretty solid.

**Comment by JesusLeon** [comment]
@DanielDarrenJones sure, it already runs within a queued job, so no need to re-queue :)

**Comment by mattstauffer** [comment]
Thanks @JesusLeon! :)
