### ISSUE TITLE
Skip processing any comments with `created_at` and `modified_at` dates prior to the last cron job

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/giscus#20]
This could limit the number of database lookups we're doing.

**Comment by anthonyterrell** [comment]
#51 Adds eager loading, which limits the number of database lookups inside `NotifyUsersOfNewGistComments` job. 

In addition, this could potentially drop notifications if there are any failures or lags in the queue processing and we rely on a 100% success rate.
