### ISSUE TITLE
Question: Why does it require read and write access to gists?

### ISSUE THREAD

**Issue by Vadorequest** [tightenco/giscus#23]
I don't understand why this application requires read and **write** access. Why isn't readonly sufficient?

![image](https://cloud.githubusercontent.com/assets/3807458/19399267/002ff74e-9251-11e6-89ae-32d73edca800.png)

Could you please explain the reason? Also, I think the explanation should be added on the README too.
Thank you :)

**Comment by mattstauffer** [comment]
You can see it here:

https://github.com/tightenco/giscus/issues/15

Basically, GitHub doesn't give us any fidelity in requesting Gist access. It's either all or nothing, unfortunately.

I'm perfectly OK with someone PR'ing an explanation to the README.

Thanks!
