### ISSUE TITLE
Email hits some SpamAssassin criteria

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/giscus#24]
(Via Marcel Stör)

>  0.7 MIME_HTML_ONLY         BODY: Message only has text/html MIME parts
- Send Text, not just HTML versions

>  0.4 HTML_MIME_NO_HTML_TAG  HTML-only message, but there is no HTML tag
- Add <html> tags around final email structure

**Comment by marcelstoer** [comment]
https://github.com/tightenco/giscus/blob/master/resources/views/emails/new-comment.blade.php is the right file to modify?

Laravel allows sending text alongside HTML. https://laravel.com/docs/5.3/mail#configuring-the-view is the right pointer I believe?

It may be a bit difficult to test though for an outsider.
