### ISSUE TITLE
Notify on gists that I've commented in

### ISSUE THREAD

**Issue by protist** [tightenco/giscus#25]
I'm not sure if this is even possible, but it'd be great is giscus could notify not only on gists that *I've* created, but also on gists that *others* have made, and I have commented on.

**Comment by mattstauffer** [comment]
@protist I totally agree! I really wish we could also get @ mentions for our names.

Sadly, that's entirely impossible--that information isn't exposed via the API at all.

Thanks for the suggestion though!

**Comment by protist** [comment]
Argh, I guess we shouldn't expect GitHub to provide that information if they don't even notify on gists normally! 😞

Thanks for the quick reply, though! Cheers.

**Comment by brondsem** [comment]
What about having a form where I can manually tell Giscus what gists to follow?

**Comment by mattstauffer** [comment]
@brondsem that's a super interesting idea. If people liked the idea there could be a chrome plugin that says "follow this gist" as a little button somewhere on the page.
