### ISSUE TITLE
Implement redesign per @sschoger <3

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/giscus#28]
![image](https://user-images.githubusercontent.com/151829/31020543-48f37910-a501-11e7-9ab6-569e4b57d824.png)

Per steve: "This page still needs work. Currently missing some content."

**Comment by tucq88** [comment]
Do we got a psd or sketch for this?

**Comment by mattstauffer** [comment]
@tucq88 I can ping @sschoger for it.

**Comment by sschoger** [comment]
![annotations](https://user-images.githubusercontent.com/2652515/31146154-adc6ddc8-a853-11e7-8edd-495f961c56a8.png)
![design](https://user-images.githubusercontent.com/2652515/31146155-add98b3a-a853-11e7-8824-2ee2d4079ac7.png)
[SVG assets.zip](https://github.com/tightenco/giscus/files/1353660/SVG.assets.zip)

**Comment by tucq88** [comment]
Seems like we only get image as guide for new design. It would much easier with Sketch/PSD file :(

**Comment by mattstauffer** [comment]
@tucq88 what would you get from a Sketch file that you don't have from steve's comment above?

**Comment by tucq88** [comment]
I mean spacing, fontsize, typo etc :D If not I would have to guess

**Comment by tucq88** [comment]
Oh no, why I don't see the image with css guidances from Stev. Sorry. seems all good now. I would like to take this (cheers)
