### ISSUE TITLE
Unsubscribe link

### ISSUE THREAD

**Issue by CMCDragonkai** [tightenco/giscus#31]
Hey I just received this notification. It's pretty cool, but I actually forgot when or if I ever signed up to this. At any case, I like this service.

But I think you should be giving an unsubscribe link at the bottom of each notification email, it's probably needed according to some spam laws.

**Comment by mattstauffer** [comment]
I think this is a fantastic idea. Thanks for the idea!

**Comment by mattstauffer** [comment]
I'd still love us to do another step with a true unsubscribe link, but the commit above at least adds directions.

**Comment by jakebathman** [comment]
I can get that going. Here's how it might go:

#### 1. Click Unsubscribe link (add to all emails)

https://giscus.co/unsubscribe?id=43112&verify=abcde12345

Where `id` is the user's `github_id` and the `verify` parameter is a hash of the user's `github_id` and `token` fields, used to verify the user when clicking the link.

#### 2. Check the hash 
Retrieve the user associated with the given `github_id`, hash that with their `token` and compare to the `verify` param. 

If it matches, redirect to step 3 below.

If it doesn't match, show a small error view.

#### 3. Confirm unsubscribe

We can probably re-use the current view at `/user/confirm-cancel`, but with a different `h2`:
![image](https://user-images.githubusercontent.com/43112/31909863-1e8ee73c-b801-11e7-9595-4f89e404d21b.png)

**Comment by mattstauffer** [comment]
@jakebathman I like it. :)
