### ISSUE TITLE
GitHub OAuth scope for writing gists

### ISSUE THREAD

**Issue by jakebathman** [tightenco/giscus#41]
I was just about to link a different GitHub account to Giscus, and noticed that the GitHub OAuth prompt says this project is requesting _read and write_ access to public and private gists.

I haven't seen whether this app is meant to check _private_ gists, which is definitely fine. Just wanted to make sure it wasn't over-requesting any scopes that aren't necessary.

From the GitHub docs, these are the current scopes being requested:

**Name**|**Description**
:-----:|:-----:
**(no scope)**|Grants read-only access to public information (includes public user profile info, public repository info, and gists)
**gist**|Grants write access to gists.
**user:email**|Grants read access to a user's email addresses.

If we don't care about private gists, we can remove the **gist** scope, revising the method in `AuthController.php`:

```php
    public function redirectToProvider()
    {
        return Socialite::driver('github')
            ->scopes(['user:email'])
            ->redirect();
    }
```

**Comment by mattstauffer** [comment]
Yep, it's for private gists. Thanks!
