### ISSUE TITLE
Add a checkbox that allows users to decide whether they want to add the`gist` scope

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/giscus#45]
In order to read private Gists, we have to ask for the `gist` scope from GitHub. But some people don't trust us enough to give us write access to their gists (and GitHub has not separated "read private gists" from "write to gists", annoyingly), and others don't want reminders on their private gists.

It'd be nice if there were a checkbox/radio that allow signing-up users to define which scope they want. We don't need to do the work to add it for current users; they can just delete their account and re-sign-up (unless it's super easy to add to current users, which I doubt).

**Comment by jasonlbeggs** [comment]
I will work on it in a few minutes if no one else has already taken it!

**Comment by jasonlbeggs** [comment]
Would you like the checkbox to be checked or not by default?

**Comment by mattstauffer** [comment]
I'm leaning toward "yes" because I think anyone who sees the "we're asking for write access" might go back and un-check the checkbox, but anyone who ignores the checkbox won't have other cues to let them know that "you just opted out of notifications for a potential crap ton of your gists", so I think the checked-by-default has a lower likelihood of people being surprised.
