### ISSUE TITLE
The link straight to the comment using #gistcomment-{id} is not functioning

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/giscus#6]

**Comment by mattstauffer** [comment]
It isn't.

It links to something like this, using the comment's `html_url` param:

https://gist.github.com/cb24547d9bd69da6f5d3#gistcomment-1551919

And once that forwards to this:

https://gist.github.com/mattstauffer/cb24547d9bd69da6f5d3

It strips the anchor.

We could manually generate the link using `domain/username/id`. That makes me a BIT nervous but I think it should work?

**Comment by mattbucci** [comment]
It seems like this was fixed on github's end. https://gist.github.com/cb24547d9bd69da6f5d3#gistcomment-1551919 
links me to 
https://gist.github.com/mattstauffer/cb24547d9bd69da6f5d3#gistcomment-1551919

**Comment by mattstauffer** [comment]
Woo!!! Nice catch @mattbucci
