### ISSUE TITLE
Pagination caching causing notifications to potentially be sent to incorrect users

### ISSUE THREAD

**Issue by loganhenson** [tightenco/giscus#61]
The implementation for generating an `id` for each request does not create unique pagination request `id`s (`vendor/knplabs/github-api/lib/Github/HttpClient/CachedHttpClient.php`).

This causes potentially undefined behavior when used in a multithreaded context + pagination with caching.

For now, the queue workers have been disabled. We can either:
A) Disable caching and reenable the queue workers
B) Upgrade to the latest version of the library where the pagination + cache implementation has been fixed
C) Find a way to patch it from userland
D) Drop the dependency and use the graphql to eager load the users most recent 100 gists + their most recent 100 comments to negate the need for caching and pagination.

I recommend D)

Graphql query:
```
{
  viewer {
    gists(first: 100, privacy: PUBLIC, orderBy: {field: UPDATED_AT, direction: DESC}) {
      edges {
        node {
          id
          updatedAt
          description
          comments(last: 100) {
            edges {
              node {
                id
                bodyHTML
                createdAt
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by mattstauffer** [comment]
I definitely prefer B for now. Let's fix it, get the queue workers going again, and then we can consider GraphQL later.

But I don't like the GraphQL that's written here; last 100 gists will not work for anyone who gets comments on older gists. Last 100 comments totally makes sense, if we could get it on all gists ever performantly?
