### ISSUE TITLE
Remove login button & checkbox from homepage

### ISSUE THREAD

**Issue by jakebathman** [tightenco/giscus#71]
Since Giscus is now retired (after GitHub added this functionality natively) we no longer need to have a login button on the main page.

This button, and the "Allow us to access your private Gists" checkbox, should be removed from the `resources/views/welcome` view.

**Comment by jodylecompte** [comment]
Hi @jakebathman 👋 I'd like to work on this

**Comment by mattstauffer** [comment]
To-be-closed by #72
